# roles/ROLENAME/tasks/main.yml
---

- name: Load OS/distribution dependent variables
  include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution }}.yml"
    - "{{ ansible_os_family }}.yml"
  tags: ROLENAME

- name: Install packages
  package:
    name: "{{ item }}"
    state: present
  with_items: "{{ ROLENAME_packages }}"
  tags: ROLENAME

- name: Ensure service is started
  service:
    name: "{{ ROLENAME_service }}"
    state: started
    enabled: true
  tags: ROLENAME
