---
# Remark: Common variables are defined in `group_vars/all.yml`

- name: Converge
  hosts: all
  vars:
  # Define role variables here
  roles:
    - role: "{{ lookup('env', 'MOLECULE_PROJECT_DIRECTORY') | basename }}"
